version: "3.7"

services:
  database:
    container_name: mongo-database
    image: mongo:4.2
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: challenge
    networks:
        - nestjs-network
networks:
    nestjs-network:
      driver: bridge